export const HAS_ONBOARDED = "HAS_ONBOARDED"
export const USER_PUBLIC_KEY = "USER_PUBLIC_KEY"
export const BASE_58_PUBLIC_KEY = "BASE_58_PUBLIC_KEY"
export const AUTH_TOKEN = "AUTH_TOKEN"
export const USER_ROLE = "USER_ROLE"
export const SIGNATURE = "SIGNATURE"
export const SIGNATURE_MESSAGE = "SIGNATURE_MESSAGE"
export const SERVER_AUTH_TOKEN = "SERVER_AUTH_TOKEN"

