import { Chat } from "@/@types/chat"

export const dummy_chats: Chat[] = [
  {
    chat_id: "chat_001",
    createdAt: "2025-04-14T10:15:00Z",
    last_message: "Hey! Are you coming tonight?",
    messageType: "text",
    user: {
      name: "Alice Johnson",
      profile_url: "https://randomuser.me/api/portraits/women/1.jpg",
      online_status: true,
    },
    is_read: false,
    unread_message_count: 2,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_002",
    createdAt: "2025-04-13T08:45:00Z",
    last_message: "📸",
    messageType: "image",
    user: {
      name: "Bob Smith",
      profile_url: "https://randomuser.me/api/portraits/men/2.jpg",
      online_status: false,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: true,
    from_me: true,
  },
  {
    chat_id: "chat_003",
    createdAt: "2025-04-14T11:00:00Z",
    last_message: "Got it, thanks!",
    messageType: "text",
    user: {
      name: "Clara Lee",
      profile_url: "https://randomuser.me/api/portraits/women/3.jpg",
      online_status: true,
    },
    is_read: false,
    unread_message_count: 1,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_004",
    createdAt: "2025-04-12T20:22:00Z",
    last_message: "Check this out 🖼️",
    messageType: "image",
    user: {
      name: "Daniel Wu",
      profile_url: "https://randomuser.me/api/portraits/men/4.jpg",
      online_status: false,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: false,
    from_me: true,
  },
  {
    chat_id: "chat_005",
    createdAt: "2025-04-10T18:30:00Z",
    last_message: "Let's catch up this weekend.",
    messageType: "text",
    user: {
      name: "Ella Nguyen",
      profile_url: "https://randomuser.me/api/portraits/women/5.jpg",
      online_status: true,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_006",
    createdAt: "2025-04-13T22:50:00Z",
    last_message: "Where are you now?",
    messageType: "text",
    user: {
      name: "Felix Ramirez",
      profile_url: "https://randomuser.me/api/portraits/men/6.jpg",
      online_status: false,
    },
    is_read: false,
    unread_message_count: 3,
    delivered: false,
    from_me: true,
  },
  {
    chat_id: "chat_007",
    createdAt: "2025-04-14T01:30:00Z",
    last_message: "Nice meeting you!",
    messageType: "text",
    user: {
      name: "Gina Torres",
      profile_url: "https://randomuser.me/api/portraits/women/7.jpg",
      online_status: true,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: true,
    from_me: true,
  },
  {
    chat_id: "chat_008",
    createdAt: "2025-04-14T05:10:00Z",
    last_message: "🎉🎉🎉",
    messageType: "text",
    user: {
      name: "Harry Kim",
      profile_url: "https://randomuser.me/api/portraits/men/8.jpg",
      online_status: false,
    },
    is_read: false,
    unread_message_count: 4,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_009",
    createdAt: "2025-04-09T09:00:00Z",
    last_message: "Let me know when you're free.",
    messageType: "text",
    user: {
      name: "Isla Bennett",
      profile_url: "https://randomuser.me/api/portraits/women/9.jpg",
      online_status: true,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: true,
    from_me: true,
  },
  {
    chat_id: "chat_010",
    createdAt: "2025-04-13T14:55:00Z",
    last_message: "Sent you the docs.",
    messageType: "text",
    user: {
      name: "Jack O'Neil",
      profile_url: "https://randomuser.me/api/portraits/men/10.jpg",
      online_status: false,
    },
    is_read: false,
    unread_message_count: 1,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_011",
    createdAt: "2025-04-14T06:30:00Z",
    last_message: "This meme is hilarious 😂",
    messageType: "image",
    user: {
      name: "Kira Patel",
      profile_url: "https://randomuser.me/api/portraits/women/11.jpg",
      online_status: true,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: true,
    from_me: false,
  },
  {
    chat_id: "chat_012",
    createdAt: "2025-04-12T15:40:00Z",
    last_message: "I'll call you later.",
    messageType: "text",
    user: {
      name: "Liam Walker",
      profile_url: "https://randomuser.me/api/portraits/men/12.jpg",
      online_status: false,
    },
    is_read: false,
    unread_message_count: 2,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_013",
    createdAt: "2025-04-11T12:10:00Z",
    last_message: "Can you review this?",
    messageType: "text",
    user: {
      name: "Maya Chen",
      profile_url: "https://randomuser.me/api/portraits/women/13.jpg",
      online_status: true,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: true,
    from_me: true,
  },
  {
    chat_id: "chat_014",
    createdAt: "2025-04-14T07:15:00Z",
    last_message: "😍😍😍",
    messageType: "text",
    user: {
      name: "Noah Blake",
      profile_url: "https://randomuser.me/api/portraits/men/14.jpg",
      online_status: true,
    },
    is_read: false,
    unread_message_count: 5,
    delivered: false,
    from_me: false,
  },
  {
    chat_id: "chat_015",
    createdAt: "2025-04-14T03:35:00Z",
    last_message: "All set!",
    messageType: "text",
    user: {
      name: "Olivia Park",
      profile_url: "https://randomuser.me/api/portraits/women/15.jpg",
      online_status: false,
    },
    is_read: true,
    unread_message_count: 0,
    delivered: true,
    from_me: false,
  },
]
